#!/usr/bin/env python3
"""Generate ZMK chord combos for word completion.

Produces config/chords.dtsi with macros and combos for the Gallium layout.
Each chord is one or more letter keys pressed simultaneously with space.

Usage:
    python3 scripts/gen-chords.py          # generate config/chords.dtsi
    python3 scripts/gen-chords.py --dry    # print to stdout without writing

Edit the CHORDS list below to add, remove, or modify word chords.
"""

import sys
from pathlib import Path

# ── Gallium v2 letter → key position on Sofle 60-key ──────────────
GALLIUM_POS = {
    "b": 13, "l": 14, "d": 15, "c": 16, "v": 17,
    "j": 18, "y": 19, "o": 20, "u": 21,
    "n": 25, "r": 26, "t": 27, "s": 28, "g": 29,
    "p": 30, "h": 31, "a": 32, "e": 33, "i": 34,
    "x": 37, "q": 38, "m": 39, "w": 40, "z": 41,
    "k": 44, "f": 45,
}

# Thumb space keys (left inner, right inner)
SPACE_L = 53
SPACE_R = 56

# Combo timeout — all chord keys must be pressed within this window (ms)
COMBO_TIMEOUT = 50

# ── Chord definitions ─────────────────────────────────────────────
# Each entry: (word, [chord_keys])
# The chord fires when all chord_keys + space are pressed together.
CHORDS = [
    ("the",  ["t"]),
    ("be",   ["b"]),
    ("and",  ["a"]),
    ("in",   ["i"]),
    ("have", ["h"]),
    ("that", ["t", "h"]),
    ("for",  ["f"]),
    ("not",  ["n"]),
    ("with", ["w"]),
    ("you",  ["y"]),
    ("this", ["t", "s"]),
    ("from", ["f", "r"]),
    ("but",  ["b", "t"]),
    ("what", ["w", "h"]),
    ("can",  ["c"]),
]


# ── Code generation ───────────────────────────────────────────────
def zmk_keys(word: str) -> str:
    """Convert a word to ZMK &kp bindings."""
    return " ".join(f"&kp {ch.upper()}" for ch in word)


def gen_macro(name: str, word: str) -> str:
    return (
        f"        wm_{name}: wm_{name} {{\n"
        f"            compatible = \"zmk,behavior-macro\";\n"
        f"            #binding-cells = <0>;\n"
        f"            wait-ms = <0>;\n"
        f"            tap-ms = <0>;\n"
        f"            bindings = <{zmk_keys(word)} &kp SPACE>;\n"
        f"        }};"
    )


def gen_combo(name: str, positions: list[int], space_pos: int, suffix: str) -> str:
    all_pos = sorted(positions + [space_pos])
    pos_str = " ".join(str(p) for p in all_pos)
    return (
        f"        chord_{name}_{suffix} {{\n"
        f"            bindings = <&wm_{name}>;\n"
        f"            key-positions = <{pos_str}>;\n"
        f"            timeout-ms = <{COMBO_TIMEOUT}>;\n"
        f"        }};"
    )


def generate_dtsi() -> str:
    macros = []
    combos = []

    for word, keys in CHORDS:
        name = word.replace("'", "_")
        positions = [GALLIUM_POS[k] for k in keys]

        macros.append(gen_macro(name, word))
        combos.append(gen_combo(name, positions, SPACE_L, "l"))
        combos.append(gen_combo(name, positions, SPACE_R, "r"))

    return (
        "/* Auto-generated by scripts/gen-chords.py — do not edit by hand */\n"
        "\n"
        "/ {\n"
        "    macros {\n"
        + "\n\n".join(macros) + "\n"
        "    };\n"
        "\n"
        "    combos {\n"
        "        compatible = \"zmk,combos\";\n"
        "\n"
        + "\n\n".join(combos) + "\n"
        "    };\n"
        "};\n"
    )


def main():
    dtsi = generate_dtsi()

    if "--dry" in sys.argv:
        print(dtsi)
        return

    out = Path(__file__).resolve().parent.parent / "config" / "chords.dtsi"
    out.write_text(dtsi)
    print(f"Generated {out.relative_to(out.parent.parent)}")
    print(f"  {len(CHORDS)} words, {len(CHORDS) * 2} combos (L+R space)")


if __name__ == "__main__":
    main()
